Repository Kotlin-Android-Study-with-SSAFY/Quiz-Cafe-Android, pull requests merged in 2025-06, with the labels that each got.

#22 [SQC-103][SQC-104][SQC-105] 문제풀기 UI 구현
  app/src/main/java/com/android/quizcafe/core/designsystem/theme/Color.kt
  app/src/main/java/com/android/quizcafe/feature/quiz/solve/QuizSolveRoute.kt
  app/src/main/java/com/android/quizcafe/feature/quiz/solve/QuizSolveScreen.kt
  app/src/main/java/com/android/quizcafe/feature/quiz/solve/component/ExplanationSection.kt
  app/src/main/java/com/android/quizcafe/feature/quiz/solve/component/MultipleChoiceOptionButton.kt
  app/src/main/java/com/android/quizcafe/feature/quiz/solve/component/QuizTopBar.kt
  app/src/main/java/com/android/quizcafe/feature/quiz/solve/component/UnderlinedTextField.kt
  app/src/main/java/com/android/quizcafe/feature/quiz/solve/viewmodel/QuizSolveEffect.kt
  app/src/main/java/com/android/quizcafe/feature/quiz/solve/viewmodel/QuizSolveIntent.kt
  app/src/main/java/com/android/quizcafe/feature/quiz/solve/viewmodel/QuizSolveUiState.kt
  app/src/main/java/com/android/quizcafe/feature/quiz/solve/viewmodel/QuizSolveViewModel.kt
  app/src/main/java/com/android/quizcafe/main/navigation/QuizCafeNavHost.kt
  app/src/main/java/com/android/quizcafe/main/navigation/routes/QuizSolveRoute.kt
  app/src/main/res/drawable/ic_arrow_back.xml
  app/src/main/res/drawable/ic_sidebar.xml
  app/src/main/res/drawable/ic_timer.xml
  app/src/main/res/drawable/quizcafelogo.xml
  app/src/main/res/font/jua_regular.ttf
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ✨ Feature

#26 [SQC-109] QuizScreen ViewModel, Domain, Data 구현
  .editorconfig
  app/src/main/java/com/android/quizcafe/core/data/di/DataModule.kt
  app/src/main/java/com/android/quizcafe/core/data/di/ServiceModule.kt
  app/src/main/java/com/android/quizcafe/core/data/model/quizsolvingrecord/response/QuizSolvingRecordResponseDto.kt
  app/src/main/java/com/android/quizcafe/core/data/remote/datasource/QuizSolvingRecordRemoteDataSource.kt
  app/src/main/java/com/android/quizcafe/core/data/remote/service/QuizSolvingRecordService.kt
  app/src/main/java/com/android/quizcafe/core/data/repository/QuizSolvingRecordRepositoryImpl.kt
  app/src/main/java/com/android/quizcafe/core/domain/model/quizsolvingrecord/response/McqOption.kt
  app/src/main/java/com/android/quizcafe/core/domain/model/quizsolvingrecord/response/Quiz.kt
  app/src/main/java/com/android/quizcafe/core/domain/model/quizsolvingrecord/response/QuizSolvingRecord.kt
  app/src/main/java/com/android/quizcafe/core/domain/repository/QuizSolvingRecordRepository.kt
  app/src/main/java/com/android/quizcafe/core/domain/usecase/quizsolvingrecord/GetQuizRecordUseCase.kt
  app/src/main/java/com/android/quizcafe/feature/categorypicker/CategoryContract.kt
  app/src/main/java/com/android/quizcafe/feature/categorypicker/CategoryPickerContent.kt
  app/src/main/java/com/android/quizcafe/feature/categorypicker/CategoryPickerScreen.kt
  app/src/main/java/com/android/quizcafe/feature/categorypicker/CategoryRoute.kt
  app/src/main/java/com/android/quizcafe/feature/categorypicker/CategoryViewModel.kt
  app/src/main/java/com/android/quizcafe/feature/login/LoginViewModel.kt
  app/src/main/java/com/android/quizcafe/feature/main/BottomNavigationBar.kt
  app/src/main/java/com/android/quizcafe/feature/main/MainScreen.kt
  app/src/main/java/com/android/quizcafe/feature/main/home/HomeContract.kt
  app/src/main/java/com/android/quizcafe/feature/main/home/HomeRoute.kt
  app/src/main/java/com/android/quizcafe/feature/main/home/HomeScreen.kt
  app/src/main/java/com/android/quizcafe/feature/main/home/HomeViewModel.kt
  app/src/main/java/com/android/quizcafe/feature/main/home/QuizModeContent.kt
  app/src/main/java/com/android/quizcafe/feature/main/home/QuizRecordContent.kt
  app/src/main/java/com/android/quizcafe/feature/main/quiz/QuizContract.kt
  app/src/main/java/com/android/quizcafe/feature/main/quiz/QuizHistorySection.kt
  app/src/main/java/com/android/quizcafe/feature/main/quiz/QuizViewModel.kt
  app/src/main/java/com/android/quizcafe/feature/util/LocalDateExt.kt
  app/src/main/java/com/android/quizcafe/main/navigation/QuizCafeNavHost.kt
  app/src/main/java/com/android/quizcafe/main/navigation/routes/MainRoute.kt
  app/src/main/res/drawable/ic_person_outline.xml
  app/src/main/res/drawable/ic_quiz_making.xml
  app/src/main/res/drawable/ic_quiz_multiple_choice.xml
  app/src/main/res/drawable/ic_quiz_ox.xml
  app/src/main/res/drawable/ic_quiz_short_answer.xml
  app/src/main/res/values/strings.xml
Labels: ✨ Feature, 1️⃣ Ver 1

#31 [SQC-114] GoogleLogin Client 구현
  .github/workflows/ci.yml
  app/build.gradle.kts
  app/src/main/java/com/android/quizcafe/core/data/model/auth/request/GoogleLoginRequestDto.kt
  app/src/main/java/com/android/quizcafe/core/data/remote/datasource/AuthRemoteDataSource.kt
  app/src/main/java/com/android/quizcafe/core/data/remote/service/AuthService.kt
  app/src/main/java/com/android/quizcafe/core/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/android/quizcafe/core/designsystem/theme/Color.kt
  app/src/main/java/com/android/quizcafe/core/domain/repository/AuthRepository.kt
  app/src/main/java/com/android/quizcafe/core/domain/usecase/auth/GoogleLoginUseCase.kt
  app/src/main/java/com/android/quizcafe/feature/login/LoginContent.kt
  app/src/main/java/com/android/quizcafe/feature/login/LoginContract.kt
  app/src/main/java/com/android/quizcafe/feature/login/LoginRoute.kt
  app/src/main/java/com/android/quizcafe/feature/login/LoginScreen.kt
  app/src/main/java/com/android/quizcafe/feature/login/LoginViewModel.kt
  app/src/main/res/drawable/google_logo.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ✨ Feature, 1️⃣ Ver 1

#34 [SQC-114] Google 소셜 로그인 리팩토링
  app/src/main/java/com/android/quizcafe/core/data/remote/datasource/QuizBookSolvingRemoteDataSource.kt
  app/src/main/java/com/android/quizcafe/core/data/repository/QuizBookSolvingRepositoryImpl.kt
  app/src/main/java/com/android/quizcafe/core/datastore/AuthManager.kt
  app/src/main/java/com/android/quizcafe/core/datastore/di/AuthModule.kt
  app/src/main/java/com/android/quizcafe/core/datastore/di/GoogleAuthManager.kt
  app/src/main/java/com/android/quizcafe/feature/login/LoginContract.kt
  app/src/main/java/com/android/quizcafe/feature/login/LoginRoute.kt
  app/src/main/java/com/android/quizcafe/feature/login/LoginViewModel.kt
  app/src/main/java/com/android/quizcafe/feature/quiz/solve/QuizSolveScreen.kt
  app/src/main/java/com/android/quizcafe/feature/quiz/solve/viewmodel/QuizSolveViewModel.kt
  app/src/main/java/com/android/quizcafe/feature/quiz/solvingResult/QuizBookSolvingResultRoute.kt
Labels: 1️⃣ Ver 1, 🔨 Refactor
